lab:
  nodes:
    pve-01:
    pve-02:
    pve-03:
  dns:
    - 10.0.0.19
  tz: America/Chicago
  node: pve-01
  github_username: pezhore
  fqdn: lan.pezlab.dev
  users:
    terraform-prov@pve:
      groups: terraform
    packer@pve:
      groups: packer
  acls:
    terraform:
      privileges:
      - VM.Allocate 
      - VM.Clone 
      - VM.Config.CDROM 
      - VM.Config.CPU 
      - VM.Config.Cloudinit 
      - VM.Config.Disk 
      - VM.Config.HWType 
      - VM.Config.Memory 
      - VM.Config.Network 
      - VM.Config.Options 
      - VM.Monitor 
      - VM.Audit 
      - VM.PowerMgmt
      - Datastore.AllocateSpace
      - Datastore.Audit
    packer:
      privileges:
        - VM.Config.Disk
        - VM.Config.CPU
        - VM.Config.Memory
        - Datastore.AllocateSpace
        - Sys.Modify
        - VM.Config.Options
        - VM.Allocate
        - VM.Audit
        - VM.Console
        - VM.Config.CDROM
        - VM.Config.Network
        - VM.PowerMgmt
        - VM.Config.HWType
        - VM.Monitor
cloud_images:
  focal:
  jammy:
core_vms:
  powerdns:
    template: ubuntu-2204-template
    node: pve-01
    description: PowerDNS server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    memory: 2048
    vm_id: 101
    scsihw: virtio-scsi-pci
    dynamic:
      disks:
        disk0:
          size: 30G
          storage: cephfs
          type: scsi
          format: qcow2
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipaddr: 10.0.0.241/24
    gateway: 10.0.0.1
  netbox:
    template: ubuntu-2204-template
    node: pve-01
    description: Netbox server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    memory: 2048
    vm_id: 102
    scsihw: virtio-scsi-pci
    dynamic:
      disks:
        disk0:
          size: 30G
          storage: cephfs
          type: scsi
          format: qcow2
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipaddr: 10.0.0.40/24
    gateway: 10.0.0.1
  freeipa:
    template: ubuntu-2204-template
    node: pve-01
    description: FreeIPA server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    memory: 2048
    vm_id: 103
    scsihw: virtio-scsi-pci
    dynamic:
      disks:
        disk0:
          size: 30G
          storage: cephfs
          type: scsi
          format: qcow2
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipaddr: 10.0.0.243/24
    gateway: 10.0.0.1