lab:
  api_host: 10.0.0.211
  nodes:
    - pve-01
    - pve-02
    - pve-03
  dns:
    - 10.0.0.19
  nameserver: 10.0.0.19
  tz: America/Chicago
  node: pve-01
  github_username: pezhore
  fqdn: lan.pezlab.dev
  users:
    terraform-prov@pve:
      groups: terraform
    packer@pve:
      groups: packer
  acls:
    terraform:
      privileges:
      - VM.Allocate 
      - VM.Clone 
      - VM.Config.CDROM 
      - VM.Config.CPU 
      - VM.Config.Cloudinit 
      - VM.Config.Disk 
      - VM.Config.HWType 
      - VM.Config.Memory 
      - VM.Config.Network 
      - VM.Config.Options 
      - VM.Monitor 
      - VM.Audit 
      - VM.PowerMgmt
      - Datastore.AllocateSpace
      - Datastore.Audit
    packer:
      privileges:
        - VM.Config.Disk
        - VM.Config.CPU
        - VM.Config.Memory
        - Datastore.AllocateSpace
        - Sys.Modify
        - VM.Config.Options
        - VM.Allocate
        - VM.Audit
        - VM.Console
        - VM.Config.CDROM
        - VM.Config.Network
        - VM.PowerMgmt
        - VM.Config.HWType
        - VM.Monitor
cloud_images:
  focal:
  jammy:
container_images:
  bionic: http://download.proxmox.com/images/system/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz
  focal: http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04.1-1_amd64.tar.gz
  jammy: http://download.proxmox.com/images/system/ubuntu-22.04-standard_22.04.1-1_amd64.tar.gz
core_vms:
  pdns-1:
    template: jammy-template
    node: pve-03
    description: PowerDNS server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    vcpus: 1
    memory: 2048
    vmid: 100
    tags:
      - ansible
      - ubuntu
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 16G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.241
    gateway: 10.0.0.1
  pdns-2:
    template: jammy-template
    node: pve-02
    description: PowerDNS server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    vcpus: 1
    memory: 2048
    vmid: 101
    tags:
      - ansible
      - ubuntu
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 16G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.242
    gateway: 10.0.0.1
  netbox:
    template: jammy-template
    node: pve-01
    description: Netbox server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    vcpus: 1
    memory: 2048
    vmid: 102
    tags:
      - ansible
      - ubuntu
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 16G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.40
    gateway: 10.0.0.1
  freeipa:
    template: jammy-template
    node: pve-03
    description: FreeIPA server for Lab
    os_type: ubuntu
    cores: 2
    sockets: 1
    vcpus: 1
    memory: 2048
    vmid: 103
    tags:
      - ansible
      - ubuntu
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 16G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.243
    gateway: 10.0.0.1
  k8s-master:
    template: jammy-template
    node: pve-02
    description: Kubernetes Master for Lab
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 104
    tags:
      - ansible
      - ubuntu
      - kubernetes
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 88G
        storage: ds1618
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.65
    gateway: 10.0.0.1
  k8s-worker-01:
    template: jammy-template
    node: pve-03
    description: Kubernetes Worker for Lab
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 105
    tags:
      - ansible
      - ubuntu
      - kubernetes
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 168G
        storage: ds1618
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.66
    gateway: 10.0.0.1
  k8s-worker-02:
    template: jammy-template
    node: pve-01
    description: Kubernetes Worker for Lab
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 106
    tags:
      - ansible
      - ubuntu
      - kubernetes
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 168G
        storage: ds1618
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.67
    gateway: 10.0.0.1
  k8s-worker-03:
    template: jammy-template
    node: pve-02
    description: Kubernetes Worker for Lab
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 107
    tags:
      - ansible
      - ubuntu
      - kubernetes
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 168G
        storage: ds1618
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.68
    gateway: 10.0.0.1
  k8s-worker-04:
    template: jammy-template
    node: pve-02
    description: Kubernetes Worker for Lab
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 108
    tags:
      - ansible
      - ubuntu
      - kubernetes
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 168G
        storage: ds1618
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.69
    gateway: 10.0.0.1
  minecraft:
    template: jammy-template
    node: pve-03
    description: Minecraft server
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 210
    tags:
      - ansible
      - ubuntu
      - minecraft
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 30G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.30
    gateway: 10.0.0.1
  docker:
    template: jammy-template
    node: pve-03
    description: Minecraft server
    os_type: ubuntu
    cores: 2
    sockets: 2
    vcpus: 2
    memory: 4096
    vmid: 211
    tags:
      - ansible
      - ubuntu
      - docker
    scsihw: virtio-scsi-pci
    disks:
      scsi0:
        size: 60G
        storage: ceph-vm
        type: scsi
        format: qcow2
    dynamic:
      networks:
        net0:
          model: virtio
          bridge: vmbr0
    ipv4: 10.0.0.31
    gateway: 10.0.0.1
containers:
  wireguard:
    ipv4: 10.0.0.122
    gateway: 10.0.0.1
    node: pve-01
    image: jammy
    vmid: 2048
    tags:
      - ansible
      - ubuntu
