- hosts: all
  become: true

  tasks:

    - name: Set the ubuntu user's password to the password stored in vault
      ansible.builtin.user:
        name: ubuntu
        password: "{{ lookup('hashi_vault', 'secret=homelab/data/general').ubuntu| password_hash('sha512') }}"

    - name: Install various apt packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim

    - name: Set content of our /etc/systemd/resolved.conf file
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNS=10.0.0.241
          FallbackDNS=10.0.0.242
          Domains=lan.pezlab.dev
        dest: /etc/systemd/resolved.conf
        owner: root
        group: root
        mode: 0644
      notify: restart systemd-resolved
      when: inventory_hostname not in groups['pdns']


  handlers:
    - name: restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved.service
        state: restarted
